version: "3.9"

services:
  app:
    build: .
    container_name: node-todos
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      DB_FILE: "/app/db.json"        # arquivo dentro do container
      PUBLIC_DIR: "/app/public"      # frontend
      ALLOW_ORIGINS: "*"             # ajuste conforme seu domínio
    restart: unless-stopped